# Generated by Django 2.2.16 on 2022-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220527_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='выберите изображение', upload_to='recipe/', verbose_name='ссылка на картинку на сайте'),
        ),
    ]
