# Generated by Django 2.2.16 on 2022-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220527_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe/', verbose_name='ссылка на картинку на сайте'),
        ),
    ]
