# Generated by Django 2.2.16 on 2022-06-01 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20220529_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.ManyToManyField(related_name='is_favorites', to=settings.AUTH_USER_MODEL, verbose_name='находится ли в избранном'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(related_name='is_in_carts', to=settings.AUTH_USER_MODEL, verbose_name='находится ли в корзине'),
        ),
    ]
