# Generated by Django 2.2.16 on 2022-06-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220601_2207'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_unique',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_name_length_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_measurement_unit_length_gt_0',
        ),
    ]
