# Generated by Django 2.2.16 on 2022-06-01 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220528_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.ManyToManyField(related_name='subscribes', to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(username__length__gte=3), name='\nusername слишком короткий\n'),
        ),
    ]
