# Generated by Django 2.2.16 on 2022-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220601_1904'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='\nusername слишком короткий\n',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(username__length__gte=3), name='\nusername too short\n'),
        ),
    ]
